#!/usr/bin/env bun

import { randomUUID } from "node:crypto";

import { fail } from "../../../tools/adapters/cli";
import {
  type EnsureRepoctlServerOptions,
  type RepoctlCoordinationDigest,
  type RepoctlSessionMode,
  type RepoctlSessionPhase,
  type RepoctlTaskSessionAcquireRequest,
  type RepoctlTaskSessionHeartbeatRequest,
  type RepoctlTaskSessionLeaseRecord,
  type RepoctlTaskSessionReleaseRequest,
  type RepoctlTaskSessionReleaseResponse,
  renderRepoctlCoordinationDigest,
  runRepoctlTaskSessionAcquire,
  runRepoctlTaskSessionHeartbeat,
  runRepoctlTaskSessionRelease,
} from "../../../tools/repoctl/runtime";

type OutputFormat = "json" | "shell";
type CommandName = "acquire" | "heartbeat" | "release";

type CliOptions = {
  claimedCommitUnits: string[];
  claimedHotRoots: string[];
  claimedScopeKeys: string[];
  format: OutputFormat;
  holderAgentId: string;
  mode: RepoctlSessionMode;
  phase: RepoctlSessionPhase;
  prefix: string;
  reason: string;
  repoRoot: string;
  repository: string;
  rpcTimeoutMs?: number;
  sessionId: string;
  taskId: string;
};

type Dependencies = {
  acquire: (
    request: RepoctlTaskSessionAcquireRequest,
    options: EnsureRepoctlServerOptions
  ) => Promise<RepoctlCoordinationDigest>;
  heartbeat: (
    request: RepoctlTaskSessionHeartbeatRequest,
    options: EnsureRepoctlServerOptions
  ) => Promise<RepoctlTaskSessionLeaseRecord>;
  release: (
    request: RepoctlTaskSessionReleaseRequest,
    options: EnsureRepoctlServerOptions
  ) => Promise<RepoctlTaskSessionReleaseResponse>;
  stderr: Pick<typeof process.stderr, "write">;
  stdout: Pick<typeof process.stdout, "write">;
};

const DEFAULT_DEPENDENCIES: Dependencies = {
  acquire: runRepoctlTaskSessionAcquire,
  heartbeat: runRepoctlTaskSessionHeartbeat,
  release: runRepoctlTaskSessionRelease,
  stderr: process.stderr,
  stdout: process.stdout,
};

function usage(): string {
  return `Usage:
  bun platform/dev/worktree/task-session.ts acquire --repo-root <path> --repository <owner/repo> --task-id <TASK_ID> [options]
  bun platform/dev/worktree/task-session.ts heartbeat --repo-root <path> --repository <owner/repo> --task-id <TASK_ID> --session-id <id> --phase <phase>
  bun platform/dev/worktree/task-session.ts release --repo-root <path> --repository <owner/repo> --task-id <TASK_ID> --session-id <id> --reason <text>

Options:
  --repo-root <path>              Repository root used for repoctl socket/state resolution
  --repository <owner/repo>       Canonical repository name
  --task-id <TASK_ID>             Canonical task id
  --session-id <id>               Session id (default for acquire: autogenerated)
  --holder-agent-id <id>          Holder agent id for acquire (default: wt-start)
  --mode <writer|participant|observer>
  --phase <phase>                 Session phase (default acquire/heartbeat: bootstrapping)
  --reason <text>                 Release reason (default: wt-start completed)
  --claimed-commit-unit <value>   Repeated claim
  --claimed-scope-key <value>     Repeated claim
  --claimed-hot-root <value>      Repeated claim
  --format <json|shell>           Output format (default: shell)
  --prefix <value>                Render prefix for denied coordination digests (default: wt-start)
  --rpc-timeout-ms <ms>           Override repoctl RPC timeout in milliseconds
  -h, --help                      Show this help`;
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'"'"'`)}'`;
}

function ensureNonEmpty(value: string, flag: string): string {
  const text = value.trim();
  if (!text) {
    fail(`missing value for ${flag}`);
  }
  return text;
}

function parsePositiveInteger(value: string, flag: string): number {
  const trimmed = ensureNonEmpty(value, flag);
  const parsed = Number.parseInt(trimmed, 10);
  if (!Number.isInteger(parsed) || parsed <= 0) {
    fail(`${flag} must be a positive integer, received: ${trimmed}`);
  }
  return parsed;
}

function parseArgs(argv: string[]): { command: CommandName; options: CliOptions } {
  const [commandToken, ...args] = argv;
  if (!commandToken || commandToken === "--help" || commandToken === "-h") {
    process.stdout.write(`${usage()}\n`);
    process.exit(0);
  }
  if (!["acquire", "heartbeat", "release"].includes(commandToken)) {
    fail(`unknown command: ${commandToken}`);
  }

  const options: CliOptions = {
    claimedCommitUnits: [],
    claimedHotRoots: [],
    claimedScopeKeys: [],
    format: "shell",
    holderAgentId: "wt-start",
    mode: "writer",
    phase: "bootstrapping",
    prefix: "wt-start",
    reason: "wt-start completed",
    repoRoot: "",
    repository: "",
    rpcTimeoutMs: undefined,
    sessionId: "",
    taskId: "",
  };

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    switch (arg) {
      case "--repo-root":
        options.repoRoot = ensureNonEmpty(args[index + 1] ?? "", "--repo-root");
        index += 1;
        break;
      case "--repository":
        options.repository = ensureNonEmpty(args[index + 1] ?? "", "--repository");
        index += 1;
        break;
      case "--task-id":
        options.taskId = ensureNonEmpty(args[index + 1] ?? "", "--task-id");
        index += 1;
        break;
      case "--session-id":
        options.sessionId = ensureNonEmpty(args[index + 1] ?? "", "--session-id");
        index += 1;
        break;
      case "--holder-agent-id":
        options.holderAgentId = ensureNonEmpty(args[index + 1] ?? "", "--holder-agent-id");
        index += 1;
        break;
      case "--mode":
        options.mode = ensureNonEmpty(args[index + 1] ?? "", "--mode") as RepoctlSessionMode;
        index += 1;
        break;
      case "--phase":
        options.phase = ensureNonEmpty(args[index + 1] ?? "", "--phase") as RepoctlSessionPhase;
        index += 1;
        break;
      case "--reason":
        options.reason = ensureNonEmpty(args[index + 1] ?? "", "--reason");
        index += 1;
        break;
      case "--claimed-commit-unit":
        options.claimedCommitUnits.push(
          ensureNonEmpty(args[index + 1] ?? "", "--claimed-commit-unit")
        );
        index += 1;
        break;
      case "--claimed-scope-key":
        options.claimedScopeKeys.push(ensureNonEmpty(args[index + 1] ?? "", "--claimed-scope-key"));
        index += 1;
        break;
      case "--claimed-hot-root":
        options.claimedHotRoots.push(ensureNonEmpty(args[index + 1] ?? "", "--claimed-hot-root"));
        index += 1;
        break;
      case "--format": {
        const format = ensureNonEmpty(args[index + 1] ?? "", "--format");
        if (format !== "json" && format !== "shell") {
          fail(`--format must be json or shell, received: ${format}`);
        }
        options.format = format;
        index += 1;
        break;
      }
      case "--prefix":
        options.prefix = ensureNonEmpty(args[index + 1] ?? "", "--prefix");
        index += 1;
        break;
      case "--rpc-timeout-ms":
        options.rpcTimeoutMs = parsePositiveInteger(args[index + 1] ?? "", "--rpc-timeout-ms");
        index += 1;
        break;
      case "--help":
      case "-h":
        process.stdout.write(`${usage()}\n`);
        process.exit(0);
        return {
          command: "acquire",
          options,
        };
      default:
        fail(`unknown option: ${arg}`);
    }
  }

  options.repoRoot = ensureNonEmpty(options.repoRoot, "--repo-root");
  options.repository = ensureNonEmpty(options.repository, "--repository");
  options.taskId = ensureNonEmpty(options.taskId, "--task-id");
  if (commandToken !== "acquire") {
    options.sessionId = ensureNonEmpty(options.sessionId, "--session-id");
  }

  return { command: commandToken as CommandName, options };
}

function renderAcquireShell(sessionId: string): string {
  return `WT_TASK_SESSION_ID=${shellQuote(sessionId)}\n`;
}

async function runAcquire(
  options: CliOptions,
  dependencies: Dependencies
): Promise<{ exitCode: number; sessionId: string }> {
  const sessionId = options.sessionId.trim() || `wt-start-${randomUUID()}`;
  const digest = await dependencies.acquire(
    {
      claimed_commit_units: options.claimedCommitUnits,
      claimed_hot_roots: options.claimedHotRoots,
      claimed_scope_keys: options.claimedScopeKeys,
      holder_agent_id: options.holderAgentId,
      mode: options.mode,
      repository: options.repository,
      session_id: sessionId,
      task_id: options.taskId,
    },
    {
      repoRoot: options.repoRoot,
      ...(options.rpcTimeoutMs !== undefined ? { rpcTimeoutMs: options.rpcTimeoutMs } : {}),
    }
  );

  if (digest.status !== "granted" && digest.status !== "observer_granted") {
    dependencies.stderr.write(
      `${renderRepoctlCoordinationDigest(digest, {
        heading: `task session ${digest.status} for ${options.taskId}`,
        prefix: options.prefix,
      })}\n`
    );
    return { exitCode: 1, sessionId };
  }

  if (options.format === "json") {
    dependencies.stdout.write(`${JSON.stringify({ digest, sessionId }, null, 2)}\n`);
  } else {
    dependencies.stdout.write(renderAcquireShell(sessionId));
  }
  return { exitCode: 0, sessionId };
}

async function runHeartbeat(options: CliOptions, dependencies: Dependencies): Promise<number> {
  const lease = await dependencies.heartbeat(
    {
      phase: options.phase,
      repository: options.repository,
      session_id: options.sessionId,
      task_id: options.taskId,
    },
    {
      repoRoot: options.repoRoot,
      ...(options.rpcTimeoutMs !== undefined ? { rpcTimeoutMs: options.rpcTimeoutMs } : {}),
    }
  );
  if (options.format === "json") {
    dependencies.stdout.write(`${JSON.stringify(lease, null, 2)}\n`);
  }
  return 0;
}

async function runRelease(options: CliOptions, dependencies: Dependencies): Promise<number> {
  const releaseResponse = await dependencies.release(
    {
      reason: options.reason,
      repository: options.repository,
      session_id: options.sessionId,
      task_id: options.taskId,
    },
    {
      repoRoot: options.repoRoot,
      ...(options.rpcTimeoutMs !== undefined ? { rpcTimeoutMs: options.rpcTimeoutMs } : {}),
    }
  );
  if (options.format === "json") {
    dependencies.stdout.write(`${JSON.stringify(releaseResponse, null, 2)}\n`);
  }
  return 0;
}

export async function runTaskSessionCli(
  argv: string[],
  dependencies: Dependencies = DEFAULT_DEPENDENCIES
): Promise<number> {
  const { command, options } = parseArgs(argv);
  switch (command) {
    case "acquire":
      return (await runAcquire(options, dependencies)).exitCode;
    case "heartbeat":
      return runHeartbeat(options, dependencies);
    case "release":
      return runRelease(options, dependencies);
  }
}

if (import.meta.main) {
  runTaskSessionCli(process.argv.slice(2))
    .then((exitCode) => process.exit(exitCode))
    .catch((error) => {
      process.stderr.write(`[task-session] ERROR: ${(error as Error).message}\n`);
      process.exit(1);
    });
}
